steps:
  # Step 1: Install dependencies in a virtual environment
  - name: 'python:3.9'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        python -m venv venv && \
        . venv/bin/activate && \
        pip install --upgrade pip && \
        pip install -r requirements.txt

  # Step 2: Run tests in the same environment
  - name: 'python:3.9'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        . venv/bin/activate && \
        python -m unittest discover tests

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/upgradlabs-1738334790345/amit23comp/myapp:$BUILD_ID'
      - '.'
  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/upgradlabs-1738334790345/amit23comp/myapp:$BUILD_ID'
      
images:
  - 'southamerica-east1-docker.pkg.dev/upgradlabs-1738334790345/amit23comp/myapp:$BUILD_ID'
logsBucket: "gs://amit23compow"
